services:
  frontend:
    container_name: react_frontend
    build:
      context: ./frontend
    tty: true
    ports:
      - '3000:3000'
      - '6006:6006'
    volumes:
      - ./frontend:/usr/src/frontend
      - /etc/localtime:/etc/localtime:ro # タイムゾーンを日本時刻に設定
    environment:
      TZ: Asia/Tokyo # タイムゾーンを日本時刻に設定
    security_opt:
      - seccomp:unconfined
    command: sh -c 'yarn install && yarn start'
  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/backend
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${BACKEND_PORT}:${BACKEND_CONTAINER_PORT}
    environment:
      - PORT=${BACKEND_CONTAINER_PORT}
      - MYSQL_CONTAINER_NAME=${MYSQL_CONTAINER_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
      - TZ=Asia/Tokyo
    depends_on:
      - db
    command: sh -c 'yarn install && yarn run dev'

  db:
    container_name: ${MYSQL_CONTAINER_NAME}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DEFAULT_AUTHENTICATION_PLUGIN=caching_sha2_password
      - 'TZ=Asia/Tokyo'
    image: mysql/mysql-server:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - express_output_crud_data:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT}:${MYSQL_CONTAINER_PORT}

volumes:
  express_output_crud_data:
